### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/tkl-mayan-edms#47]
Create other docs:
put them on wiki for now
- [ ] How to upgrade to latest release of Mayan
- [ ] Load sample data

**Comment by DocCyblade** [comment]
Docs are good but where should they go? Should they be with the build code, or add them to the app in a docs folder, post them on the forums?

**Comment by JedMeister** [comment]
My inclination is to put the "master" docs in a `/docs`directory within the appliance build code. There is a precedent for that, it's possibly in others too, but you can see it in both the [OpenVPN appliance](https://github.com/turnkeylinux-apps/openvpn/tree/master/docs) and [TKLDev](https://github.com/turnkeylinux-apps/tkldev/tree/master/docs). If you use RST (**R**e**S**tructured **T**ext) rather than markdown, then it renders pretty nicely in GitHub but is also really easy to convert to html (for the TurnKey website doc pages). 

On a tangent; we hope to change the way that the docs work on the website after we have upgraded the website. Ideally we'll move all the docs to GitHub and have an automated script to build static html files which will be uploaded to the website. Then editing the docs will be a case of editing the text files on GitHub...
